/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial.documentado;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Alumno
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejer2 = new javax.swing.JButton();
        ejer3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejer2.setText("Ejercicio 2");
        ejer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejer2ActionPerformed(evt);
            }
        });

        ejer3.setText("Ejercicio 3");
        ejer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejer3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejer2)
                    .addComponent(ejer3))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ejer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejer3)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejer2ActionPerformed
        
        Paciente paciente1 = new Paciente("Lionel", "Messi", 45, true, "INSSEP", "Radiologia");
        Paciente paciente2 = new Paciente("Leo", "Gonzalez", 35, true, "INSSEP", "Radiologia");
        Paciente paciente3 = new Paciente("Carlos", "Lopez", 50, true, "INSSEP", "Cardiologia");

        Turno turno1 = new Turno(1, paciente1, "12 de septiembre de 2023", "Manuel Perez");
        Turno turno2 = new Turno(2, paciente2, "12 de septiembre de 2023", "Elena Gomez");
        Turno turno3 = new Turno(3, paciente3, "12 de septiembre de 2023", "Manuel Perez");

        List<Turno> turnos = new ArrayList<>();
        turnos.add(turno1);
        turnos.add(turno2);
        turnos.add(turno3);
        
        for (Turno turno : turnos) {
            if (turno.getFecha().equals("12 de septiembre de 2023") && turno.getPaciente().getEspecialidad().equals("Radiologia")) {
                System.out.println("Numero de Turno: " + turno.getNumeroTurno());
                System.out.println("Nombre del paciente: " + turno.getPaciente().getNombre() + " " + turno.getPaciente().getApellido());
                System.out.println("Secretario/a: " + turno.getSecretario());
            }
        }
          /**
     * Acción ejecutada cuando se hace clic en el botón "Ejercicio 2".
     *
     * Este método crea pacientes y turnos, luego lista los turnos que cumplen con ciertas condiciones.
     *
     * @param evt El evento de acción que desencadena esta función.
     */
    }//GEN-LAST:event_ejer2ActionPerformed

    private void ejer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejer3ActionPerformed
        //Crear los pacientes
        Paciente paciente1 = new Paciente("Lionel", "Messi", 45, true, "INSSEP", "Radiologia");
        Paciente paciente2 = new Paciente("Leo", "Gonzalez", 35, true, "INSSEP", "Radiologia");
        Paciente paciente3 = new Paciente("Carlos", "Lopez", 50, true, "INSSEP", "Cardiologia");

        Turno turno1 = new Turno(1, paciente1, "12 de septiembre de 2023", "Manuel Perez");
        Turno turno2 = new Turno(2, paciente2, "12 de septiembre de 2023", "Elena Perez");
        Turno turno3 = new Turno(3, paciente3, "12 de septiembre de 2023", "Manuel Perez");
        //Agregarlos a una ArrayList
        List<Turno> turnos = new ArrayList<>();
        turnos.add(turno1);
        turnos.add(turno2);
        turnos.add(turno3);

        //Listar turnos por Profesional y Especialidad
        for (Turno turno : turnos) {
            System.out.println("Profesional: " + turno.getPaciente().getNombre() + " " + turno.getPaciente().getApellido());
            System.out.println("Especialidad: " + turno.getPaciente().getEspecialidad());
            System.out.println("Numero de Turno: " + turno.getNumeroTurno());
            System.out.println("Secretario/a: " + turno.getSecretario());
        }
          /**
     * Acción ejecutada cuando se hace clic en el botón "Ejercicio 3".
     *
     * Este método crea pacientes y turnos, luego lista todos los turnos.
     *
     * @param evt El evento de acción que desencadena esta función.
     */
    }//GEN-LAST:event_ejer3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ejer2;
    private javax.swing.JButton ejer3;
    // End of variables declaration//GEN-END:variables
}
